# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Joc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('preuE', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preuG', models.IntegerField()),
                ('imatge', models.ImageField(max_length=200, upload_to='jocs')),
                ('descripcio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comprat',
            name='joc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joc_comprat', to='jocs.Joc'),
        ),
        migrations.AddField(
            model_name='comprat',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
