# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprat',
            name='joc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jocs.Joc'),
        ),
    ]
